WebStaticFilesPath = "third_party/cloud_android_orchestration/web"

# List of allowed origins
# e.g. "https://localhost:8080"
CORSAllowedOrigins = ["http://localhost:39183"]

[AccountManager]
Type = "GCP"

[AccountManager.OAuth2]
Provider = "Google"
RedirectURL = "https://cloud-android-orchestrator-dev.googleplex.com/oauth2callback"

[SecretManager]
Type = "GCP"

[SecretManager.GCP]
OAuth2ClientResourceID = "projects/137388570337/secrets/cloud-android-orchestrator-oauth-client/versions/latest"

[EncryptionService]
Type = "GCP_KMS"

[EncryptionService.GCPKMS]
KeyName = "projects/google.com:cloud-android-orchestrator-dev/locations/global/keyRings/cloud-orchestrator/cryptoKeys/default"

[DatabaseService]
Type = "Spanner"

[DatabaseService.Spanner]
DatabaseName = "projects/google.com:cloud-android-orchestrator-dev/instances/cloud-orchestrator-db/databases/cloud-android-orchestrator"

[InstanceManager]
Type = "GCP"
HostOrchestratorProtocol = "https"
AllowSelfSignedHostSSLCertificate = true

[InstanceManager.GCP]
ProjectID = "google.com:cloud-android-orchestrator-dev"
HostImageFamily = "projects/google.com:cloud-android-orchestrator-dev/global/images/family/cuttlefish-orchestration-qa"
HostOrchestratorPort = 1443

[WebRTC]
STUNServers = ["stun:stun.l.google.com:19302"]

